### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by PhiLhoSoft**
Following your call on Twitter, I made a French translation.

Maybe some string / keys are obsolete: I could not find them in the sources, except in the translations. To avoid useless extra work for translators, I suggest to remove them if they are really stale.

Thanks for this great, nice site!

### CODE REVIEW

**Comment by jeresig** [comment]
Thank you so much @PhiLhoSoft! You're right that there are likely a bunch of dead strings in there, I'm sorry! I wasn't expecting such an influx of interest in helping to translate. I absolutely will clean it out to help make it easier in the future. Thank you again -- this work is just fantastic!

**Comment by ventrebleu** [comment]
Happy you got your French translation. I don't know what happened to mine though.
Cheers!

**Comment by jeresig** [comment]
@ventrebleu oh no - did you submit some? I didn't see a pull request! Did I miss it?

**Comment by ventrebleu** [comment]
No idea. I changed it directly on Github and submitted it... No big deal.

**Pull request merged**
