### PR TITLE
German (de) translation

### PR DESCRIPTION
**Pull request by FlorianHeigl**
That was the easiest parts
Includes some umlauts.

### CODE REVIEW

**Comment by FlorianHeigl** [comment]
Added a few more of the easy pieces. I find it rather tricky to guess the context for some of the texts I couldn't find on the site, but I'll try to get it right (rather less precise than awkward sounding)

The more ambiguous terms are probably whats up next :)

**Comment by jeresig** [comment]
This is fantastic, @FlorianHeigl! Please let me know if you have any questions about context or need help finding the strings. Happy to help!

**Comment by FlorianHeigl** [comment]
These are particularly confusing:

	"Language Notice": "このページの英語版を表示している。",
	"Language Redirect": "日本語版を表示します。",
	"en-US": "de-DE",

first two: I don't get what they're doing
third: is it supposed to be translated? if yes, de-DE should be OK.

**Comment by jeresig** [comment]
@FlorianHeigl Yeah, sorry - the first two are legacy from the old system (where it assumed that the other language was always Japanese or English). Feel free to leave those as-is. And you're right to make the third change. I'll need to go through and figure out if that's exactly how I want things to work in the new system, but I'm not quite sure yet.

Thank you so much for your continued work on this -- I so appreciate it!

**Pull request merged**
