### PR TITLE
pt_BR Translations.

### PR DESCRIPTION
**Pull request by FellipeBr**
Translations to pt_BR.

### CODE REVIEW

**Comment by jeresig** [comment]
Wow!!! This is amazing!! Seriously, thank you so much! I'm going to work on getting this running over the next couple days and try to get this live. I'll need to re-work some of the site logic a bit since I had assumed that there would only be two languages (English and Japanese). But no worries, I'll fix it up. Thanks again!

**Comment by PhiLhoSoft** [comment]
I found out the fr.js file.
The first two lines are a bit difficult to translate...
Specifically, the "Switch Language", "Language Notice" and "Language Redirect" keys. I actually found the English version of these in the jp.js file... Note that the "Switch Language" and "Language Redirect" parts should be improved / adjusted / replaced for more languages as they are designed as a switch / toggle between two languages.

**Comment by PhiLhoSoft** [comment]
I can translate "Japanese Woodblock prints" to "Estampes japonaises gravées sur bois", but it is a bit verbose to repeat it everywhere... Perhaps keep that for textual descriptions, and shorten to "Estampes japonaises" in labels like "Japanese Woodblock prints matching '%s'.".

**Comment by jeresig** [comment]
@PhiLhoSoft I agree, I haven't figured out yet how to handle those two first lines. And yes, "Estampes japonaises" seems to be the preferred name for the art form, in French, feel free to use it everywhere!

**Pull request merged**
